### ISSUE TITLE
Yosemite (Safari 8.0)

### ISSUE THREAD

**Issue by emc2cube** [theoldreader/safari#3]
Article count badge do not update/refresh in background.
Seems to work if one windows with The Old Reader website is open.

**Comment by krasnoukhov** [comment]
Just checked, everything works fine for me. Are you sure you have latest version installed? Also, what update interval do you use?

**Comment by emc2cube** [comment]
Version 1.6, 5min refresh.

I tried on 2 different systems with the same result. I will do further tests this night in case another extension is interfering.

**Comment by emc2cube** [comment]
Ok figured it out!
It's the new Safari cookies behavior that disrupt everything. I was on "Allow from current website only" setting but it need at least "Allow from websites I visit" permissions to work in the background. Which make total sense.

I updated the readme of my fork, if you want to add a similar information to yours:

# Safari 8.0 (Yosemite) information

Unread message badge can only be refreshed in the background if your cookies and website data preferences are either "Allow from websites I visit" or "Always allow".
It will not be able to refresh on "Allow from current website only" or "Always block" unless you are logged to theoldreader.com AND have a window or tab displaying it.

**Comment by krasnoukhov** [comment]
Ok, thanks for the investigation. Do you mind submitting a PR with README changes so it will count as your contribution?

**Comment by emc2cube** [comment]
Done.

But really feel free to refuse it and update the readme on your side, I changed a lot of other things to keep it with my additional settings, auto update from my github repo, and of course it uses my dev certificate.

**Comment by krasnoukhov** [comment]
OMG, ok, I see. Will do manually. Thanks!
